const workoutSets = [
  { name: 'Muscle', exercises: [] },
  {
    name: 'Neck',
    exercises: [
      'Exercises',
      'Lying Face Down Plate Neck Resistance',
      'Lying Face Up Plate Neck Resistance',
      'Seated Head Harness Neck Resistance',
      'Isometric Neck Exercise - Sides',
      'Isometric Neck Exercise - Front And Back',
      'Neck Bridge Prone',
      'Side Neck Stretch',
      'Chin To Chest Stretch',
      'Neck-SMR',
    ],
  },
  {
    name: 'Shoulders',
    exercises: [
      'Exercises',
      'Dumbbell front raise to lateral raise',
      'Clean and press',
      'Single-arm palm-in dumbbell shoulder press',
      'Clean and jerk',
      'Single-arm kettlebell push-press',
      'Military press',
      'Standing palms-in shoulder press',
      'Seated barbell shoulder press',
      'Seated Dumbbell Press',
      'Standing dumbbell shoulder press',
      'Single-arm lateral raise',
      'Power Partials',
      'Incline dumbbell reverse fly',
      'Overhead dumbbell front raise',
      'Seated dumbbell shoulder press',
    ],
  },
  {
    name: 'Chest',
    exercises: [
      'Exercises',
      'Dumbbell Bench Press',
      'Pushups',
      'Close-grip bench press',
      'Dumbbell Flyes',
      'Incline dumbbell bench press',
      'Low-cable cross-over',
      'Barbell Bench Press - Medium Grip',
      'Chest dip',
      'Decline Dumbbell Flyes',
      'Bodyweight Flyes',
      'Incline cable chest fly',
      'Decline barbell bench press',
      'Wide-grip bench press',
      'Wide-Grip Decline Barbell Bench Press',
      'Reverse-grip incline dumbbell bench press',
    ],
  },
  {
    name: 'Biceps',
    exercises: [
      'Exercises',
      'Incline Hammer Curls',
      'Wide-grip barbell curl',
      'EZ-bar spider curl',
      'Hammer Curls',
      'EZ-Bar Curl',
      'Zottman Curl',
      'Biceps curl to shoulder press',
      'Barbell Curl',
      'Concentration curl',
      'Flexor Incline Dumbbell Curls',
      'Machine Bicep Curl',
      'Overhead cable curl',
      'Dumbbell Bicep Curl',
      'EZ-bar spider curl',
      'Cross-body hammer curl',
    ],
  },
  {
    name: 'Triceps',
    exercises: [
      'Exercises',
      'Triceps dip',
      'Decline EZ-bar skullcrusher',
      'Dumbbell floor press',
      'Cable V-bar push-down',
      'Weighted bench dip',
      'EZ-Bar Skullcrusher',
      'Reverse Grip Triceps Pushdown',
      'Push-Ups - Close Triceps Position',
      'Kneeling cable triceps extension',
      'Single-arm cable triceps extension',
      'Triceps Pushdown - Rope Attachment',
      'Seated triceps press',
      'Incline EZ-bar skullcrusher',
      'Decline Close-Grip Bench To Skull Crusher',
      'Tricep Dumbbell Kickback',
    ],
  },
  {
    name: 'Forearm',
    exercises: [
      'Exercises',
      'Rickshaw Carry',
      'Palms-down wrist curl over bench',
      'Straight-bar wrist roll-up',
      "Dumbbell farmer's walk",
      'Palms-up wrist curl over bench',
      'Standing behind-the-back wrist curl',
      'Seated finger curl',
      'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl',
      'Wrist Roller',
      'Seated One-Arm Dumbbell Palms-Up Wrist Curl',
      'Seated Palms-Down Barbell Wrist Curl',
      'Dumbbell Lying Supination',
      'Dumbbell Lying Pronation',
      'Seated palms-up wrist curl',
      'Palms-Up Dumbbell Wrist Curl Over A Bench',
    ],
  },
  {
    name: 'Traps',
    exercises: [
      'Exercises',
      'Smith machine shrug',
      'Leverage Shrug',
      'Standing dumbbell shrug',
      'Standing dumbbell upright row',
      'Kettlebell sumo deadlift high pull',
      'Calf-Machine Shoulder Shrug',
      'Barbell shrug',
      'Barbell behind-the-back shrug',
      'Cable straight-bar upright row',
      'Cable shrug',
      'Smith machine behind-the-back shrug',
      'Upright Row - With Bands',
      'Smith machine upright row',
      'Clean Shrug',
      'Scapular Pull-Up',
    ],
  },
  {
    name: 'Lats',
    exercises: [
      'Exercises',
      'Weighted pull-up',
      'Pullups',
      'Rocky Pull-Ups/Pulldowns',
      'Close-grip pull-down',
      'Pull-up',
      'Muscle Up',
      'Shotgun row',
      'Close-Grip Front Lat Pulldown',
      'V-bar pull-up',
      'Rope climb',
      'Wide-Grip Rear Pull-Up',
      'Straight-arm rope pull-down',
      'Lat pull-down',
      'Reverse-grip lat pull-down',
      'Gironda Sternum Chins',
    ],
  },
  {
    name: 'MiddleBack',
    exercises: [
      'Exercises',
      'T-Bar Row with Handle',
      'Reverse-grip bent-over row',
      'One-Arm Dumbbell Row',
      'One-Arm Long Bar Row',
      'T-Bar Row',
      'Bent Over Two-Arm Long Bar Row',
      'Alternating sit-through with crunch',
      'Rower',
      'Seated Cable Rows',
      'Incline dumbbell row',
      'Bent Over Two-Dumbbell Row With Palms In',
      'Upside-down pull-up',
      'Bent Over Barbell Row',
      'Single-arm cable seated row',
      'Kettlebell alternating renegade row',
      'xxxxx',
    ],
  },
  {
    name: 'LowerBack',
    exercises: [
      'Exercises',
      'Atlas Stones',
      'Barbell deficit deadlift',
      'Back extension',
      'Axle Deadlift',
      'Hyperextensions With No Hyperextension Bench',
      'Deadlift with Bands',
      'Deadlift with Chains',
      'Rack Pull with Bands',
      'Superman',
      'Exercise ball weighted hyperextension',
      'Rack pull',
      'Seated Back Extension',
      'Seated Good Mornings',
      'Stiff Leg Barbell Good Morning',
      'Atlas Stone Trainer',
    ],
  },
  {
    name: 'Abs',
    exercises: [
      'Exercises',
      'Landmine twist',
      'Elbow plank',
      'Bottoms Up',
      'Suspended ab fall-out',
      'Dumbbell V-Sit Cross Jab',
      'Standing cable low-to-high twist',
      'Dumbbell spell caster',
      'Decline reverse crunch',
      'Spider crawl',
      'Cocoons',
      'Cross-Body Crunch',
      'Single-arm high-cable side bend',
      'Elbow-to-knee crunch',
      'Decline Crunch',
      'Hanging toes-to-bar',
    ],
  },
  {
    name: 'Glutes',
    exercises: [
      'Exercises',
      'Barbell glute bridge',
      'Barbell Hip Thrust',
      'Single-leg cable hip extension',
      'Glute bridge',
      'Single-leg glute bridge',
      'Step-up with knee raise',
      'Kettlebell thruster',
      'Kneeling Squat',
      'Flutter Kicks',
      'Glute Kickback',
      'Exercise ball hip thrust',
      'Kneeling Jump Squat',
      'Pull Through',
      'Hip Extension with Bands',
      'Piriformis SMR',
    ],
  },
  {
    name: 'Quads',
    exercises: [
      'Exercises',
      'Single-Leg Press',
      'Clean from Blocks',
      'Barbell Full Squat',
      'Tire flip',
      'Barbell back squat to box',
      'Push-press',
      'Power snatch-',
      'Hang Clean',
      'Reverse Band Box Squat',
      'Jumping rope',
      'Barbell walking lunge',
      'Front Squats With Two Kettlebells',
      'Single Leg Push-off',
      'Olympic Squat',
      'Stair climber',
    ],
  },
  {
    name: 'Hamstrings',
    exercises: [
      'Exercises',
      'Barbell Deadlift',
      'Romanian Deadlift With Dumbbells',
      'Clean Deadlift',
      'Sumo deadlift',
      'Romanian Deadlift from Deficit',
      'Power Snatch',
      'Power Clean from Blocks',
      'Natural Glute Ham Raise',
      'Glute ham raise-',
      'Snatch Deadlift',
      'Lying Leg Curls',
      'Stiff-Legged Dumbbell Deadlift',
      'Exercise ball leg curl',
      'Kettlebell pass-through lunge',
      'Power clean',
      'xxxxx',
    ],
  },
  {
    name: 'Calves',
    exercises: [
      'Exercises',
      'Smith Machine Calf Raise',
      'Standing Calf Raises',
      'Seated Calf Raise',
      'Calf Press On The Leg Press Machine',
      'Rocking Standing Calf Raise',
      'Calf Press',
      'Standing barbell calf raise',
      'Barbell Seated Calf Raise',
      'Balance Board',
      'Weighted donkey calf raise',
      'Smith Machine Reverse Calf Raises',
      'Dumbbell Seated One-Leg Calf Raise',
      'Ankle Circles',
      'Peroneals-SMR',
      'Knee Circles',
    ],
  },
];

export default workoutSets