export const MEASUREMENT_CREATE_REQUEST = 'MEASUREMENT_CREATE_REQUEST';
export const MEASUREMENT_CREATE_SUCCESS = 'MEASUREMENT_CREATE_SUCCESS';
export const MEASUREMENT_CREATE_FAIL = 'MEASUREMENT_CREATE_FAIL';
export const MEASUREMENT_CREATE_RESET = 'MEASUREMENT_CREATE_REMEASUREMENT';

export const MEASUREMENT_LIST_REQUEST = 'MEASUREMENT_LIST_REQUEST';
export const MEASUREMENT_LIST_SUCCESS = 'MEASUREMENT_LIST_SUCCESS';
export const MEASUREMENT_LIST_FAIL = 'MEASUREMENT_LIST_FAIL';
export const MEASUREMENT_LIST_RESET = 'MEASUREMENT_LIST_FAIL';

export const MEASUREMENT_DETAILS_REQUEST = 'MEASUREMENT_DETAILS_REQUEST';
export const MEASUREMENT_DETAILS_SUCCESS = 'MEASUREMENT_DETAILS_SUCCESS';
export const MEASUREMENT_DETAILS_FAIL = 'MEASUREMENT_DETAILS_FAIL';

export const MEASUREMENT_UPDATE_REQUEST = 'MEASUREMENT_UPDATE_REQUEST';
export const MEASUREMENT_UPDATE_SUCCESS = 'MEASUREMENT_UPDATE_SUCCESS';
export const MEASUREMENT_UPDATE_FAIL = 'MEASUREMENT_UPDATE_FAIL';

export const MEASUREMENT_DELETE_REQUEST = 'MEASUREMENT_DELETE_REQUEST';
export const MEASUREMENT_DELETE_SUCCESS = 'MEASUREMENT_DELETE_SUCCESS';
export const MEASUREMENT_DELETE_FAIL = 'MEASUREMENT_DELETE_FAIL';
