export const SET_CREATE_REQUEST = 'SET_CREATE_REQUEST';
export const SET_CREATE_SUCCESS = 'SET_CREATE_SUCCESS';
export const SET_CREATE_FAIL = 'SET_CREATE_FAIL';

export const SET_LIST_REQUEST = 'SET_LIST_REQUEST';
export const SET_LIST_SUCCESS = 'SET_LIST_SUCCESS';
export const SET_LIST_FAIL = 'SET_LIST_FAIL';

export const SET_DETAILS_REQUEST = 'SET_DETAILS_REQUEST';
export const SET_DETAILS_SUCCESS = 'SET_DETAILS_SUCCESS';
export const SET_DETAILS_FAIL = 'SET_DETAILS_FAIL';

export const SET_UPDATE_REQUEST = 'SET_UPDATE_REQUEST';
export const SET_UPDATE_SUCCESS = 'SET_UPDATE_SUCCESS';
export const SET_UPDATE_FAIL = 'SET_UPDATE_FAIL';

export const SET_DELETE_REQUEST = 'SET_DELETE_REQUEST';
export const SET_DELETE_SUCCESS = 'SET_DELETE_SUCCESS';
export const SET_DELETE_FAIL = 'SET_DELETE_FAIL';
