export const SET_CREATE_REQUEST = 'SET_CREATE_REQUEST';
export const SET_CREATE_SUCCESS = 'SET_CREATE_SUCCESS';
export const SET_CREATE_FAIL = 'SET_CREATE_FAIL';
export const SET_CREATE_RESET = 'SET_CREATE_RESET';

export const SET_DETAILS_REQUEST = 'SET_DETAILS_REQUEST';
export const SET_DETAILS_SUCCESS = 'SET_DETAILS_SUCCESS';
export const SET_DETAILS_FAIL = 'SET_DETAILS_FAIL';

export const SET_LIST_REQUEST = 'SET_LIST_REQUEST';
export const SET_LIST_SUCCESS = 'SET_LIST_SUCCESS';
export const SET_LIST_FAIL = 'SET_LIST_FAIL';
